import basicAuth from 'express-basic-auth';
import jwt from 'jsonwebtoken';
import { getAdmin, getAdminById } from '../services/admin.js';
import { validateAccessToken } from '../services/oauth.js';
import Admin from '../models/admin.js';
import { responseExceptionSilent } from '../exceptions/index.js';
import { EnvType } from '../models/environment.js';

function getBearerToken(req) {
    return req.header('Authorization')?.replace('Bearer ', '');
}

async function validateAdminJwt(token) {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const admin = await getAdminById(decoded._id);

    if (!admin?.active) {
        throw new Error('User not active');
    }
    
    if (admin.token !== Admin.extractTokenPart(token)) {
        throw new Error(`Invalid token for ${admin.email}`);
    }

    return admin;
}

/**
 * Session-only authentication middleware.
 *
 * Accepts **only** a switcher-management session JWT (as issued by
 * `Admin.generateAuthToken()`). Any other bearer token (e.g. an MCP/OAuth
 * access token) is rejected with 401.
 *
 * Use `auth` for routes that must remain strictly session-based - i.e.
 * anything not explicitly meant to be reachable by an MCP/OAuth client
 * (the default for all existing routes unless documented otherwise).
 */
export async function auth(req, res, next) {
    try {
        const token = getBearerToken(req);
        const admin = await validateAdminJwt(token);

        req.token = token;
        req.admin = admin;
        next();
    } catch (err) {
        if (err.name === 'TokenExpiredError') {
            return res.status(401).send({ error: 'Token expired.' });
        }

        responseExceptionSilent(res, err, 401, 'Please authenticate.');
    }
}

/**
 * Dual-strategy authentication middleware: accepts **either** a
 * switcher-management session JWT (`validateAdminJwt`) **or** an MCP
 * OAuth access token (`validateAccessToken`).
 *
 * Strategy order is picked heuristically from the token shape: JWTs are
 * three dot-separated base64url segments, while the opaque OAuth tokens
 * generated by `generateRandomValue()` never contain a `.`. This is a
 * heuristic, not a format guarantee - if either token format ever
 * changes, revisit this.
 *
 * Only the **first** matching strategy is tried on its "home" token
 * shape; if that strategy's token is expired (`TokenExpiredError`), the
 * request fails fast with 401 `{ error: 'Token expired.' }` rather than
 * falling through to the other strategy. If neither strategy succeeds
 * (and it wasn't an expiry), the request fails with a generic 401
 * `Please authenticate.`.
 *
 * Use `authAny` only for routes that must be reachable by both
 * switcher-management (JWT) **and** MCP/OAuth clients - as of this
 * writing: `GET /domain`, `GET /domain/collaboration`, `GET /environment`,
 * and `GET /config/key/:key`. Don't default new routes to `authAny`;
 * keep using plain `auth` unless the route is a deliberate MCP tool
 * target (see `docs/copilot/switcher-mcp/MCP_DEVELOPMENT.md`).
 */
export async function authAny(req, res, next) {
    const token = getBearerToken(req);
    const authStrategies = token?.includes('.')
        ? [validateAdminJwt, validateAccessToken]
        : [validateAccessToken, validateAdminJwt];

    try {
        for (const strategy of authStrategies) {
            try {
                const admin = await strategy(token);

                req.token = token;
                req.admin = admin;
                return next();
            } catch (err) {
                if (err.name === 'TokenExpiredError') {
                    return res.status(401).send({ error: 'Token expired.' });
                }
            }
        }

        throw new Error('Invalid token');
    } catch (err) {
        responseExceptionSilent(res, err, 401, 'Please authenticate.');
    }
}

export async function authRefreshToken(req, res, next) {
    try {
        const token = getBearerToken(req);
        const refreshToken = req.body.refreshToken;
        
        const decodedRefreshToken = jwt.verify(refreshToken, process.env.JWT_SECRET);
        if (decodedRefreshToken.subject !== Admin.extractTokenPart(token)) {
            throw new Error('Refresh code does not match');
        }

        const decoded = jwt.decode(token);
        const admin = await getAdmin({ _id: decoded._id, token: decodedRefreshToken.subject });
        
        if (!admin?.active) {
            throw new Error('User not active');
        }

        const newTokenPair = await admin.generateAuthToken();
        res.jwt = newTokenPair;
        next();
    } catch (err) {
        responseExceptionSilent(res, err, 401, 'Unable to refresh token.');
    }
}

export async function slackAuth(req, res, next) {
    try {
        const token = req.header('Authorization').replace('Bearer ', '');
        jwt.verify(token, process.env.SWITCHER_SLACK_JWT_SECRET);
        next();
    } catch (err) {
        responseExceptionSilent(res, err, 401, 'Invalid API token.');
    }
}

export async function gitopsAuth(req, res, next) {
    try {
        const token = req.header('Authorization').replace('Bearer ', '');
        const decoded = jwt.verify(token, process.env.SWITCHER_GITOPS_JWT_SECRET);

        req.token = token;
        req.domain = decoded.subject;
        req.environment = EnvType.DEFAULT;
        next();
    } catch (err) {
        responseExceptionSilent(res, err, 401, 'Invalid API token.');
    }
}

export function resourcesAuth() {
    return basicAuth({
        users: {
            admin: process.env.RESOURCE_SECRET || 'admin',
        },
        challenge: true,
    });
}