# These are supported funding model platforms

patreon: switcherapi
ko_fi: petruki
custom: ['https://www.paypal.com/donate/?business=A5R6K3JAD8SW4&no_recurring=0&item_name=Thank+you+for+supporting+the+Open+Source+Community&currency_code=CAD']
