version: '3.8'

volumes:
  mongodb_data:
    driver: local

networks:
  backend:
    driver: bridge

services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: switcher-api
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
    restart: unless-stopped

  express:
    image: switcher-api
    container_name: switcherapi
    ports:
      - '3000:3000'
    networks:
      - backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ENV=${ENV}
      - MONGODB_URI=${MONGODB_URI}
      - SENDGRID_API_KEY=S${SENDGRID_API_KEY}
      - SENDGRID_MAIL_FROM=${SENDGRID_MAIL_FROM}
      - SENDGRID_CONFIRMATION_TEMPLATE=${SENDGRID_CONFIRMATION_TEMPLATE}
      - SENDGRID_RECOVERY_TEMPLATE=${SENDGRID_RECOVERY_TEMPLATE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_CLIENT_TOKEN_EXP_TIME=${JWT_CLIENT_TOKEN_EXP_TIME}
      - JWT_ADMIN_TOKEN_RENEW_INTERVAL=${JWT_ADMIN_TOKEN_RENEW_INTERVAL}
      - MAX_EXIST_STRATEGYOPERATION=${MAX_EXIST_STRATEGYOPERATION}
      - HISTORY_ACTIVATED=${HISTORY_ACTIVATED}
      - METRICS_ACTIVATED=${METRICS_ACTIVATED}
      - METRICS_MAX_PAGE=${METRICS_MAX_PAGE}
      - GIT_OAUTH_CLIENT_ID={GIT_OAUTH_CLIENT_ID}
      - GIT_OAUTH_SECRET=${GIT_OAUTH_SECRET}
      - BITBUCKET_OAUTH_CLIENT_ID=${BITBUCKET_OAUTH_CLIENT_ID}
      - BITBUCKET_OAUTH_SECRET=${BITBUCKET_OAUTH_SECRET}
      - GOOGLE_RECAPTCHA_SECRET=${GOOGLE_RECAPTCHA_SECRET}
      - GOOGLE_SKIP_AUTH=${GOOGLE_SKIP_AUTH}

      - SWITCHER_API_ENABLE=${SWITCHER_API_ENABLE}
      - SWITCHER_API_URL=${SWITCHER_API_URL}
      - SWITCHER_API_KEY=${SWITCHER_API_KEY}
      - SWITCHER_API_DOMAIN=${SWITCHER_API_DOMAIN}
      - SWITCHER_API_ENVIRONMENT=${SWITCHER_API_ENVIRONMENT}

      - SWITCHER_SLACK_JWT_SECRET=${SWITCHER_SLACK_JWT_SECRET}
    depends_on:
      - mongodb