name: Master Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version:  16.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx eslint ./src

      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/switcher-api-test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-staging:
    name: Deploy to Staging
    needs: [ build-test ]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_1}}
          heroku_app_name: "switcher-api-staging"
          heroku_email: ${{secrets.HEROKU_EMAIL_1}}
