name: Re-release CI
run-name: Re-releasing - ${{ github.event.inputs.tag }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 6.0

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/switcher-api-test
          HISTORY_ACTIVATED: true
          JWT_ADMIN_TOKEN_RENEW_INTERVAL: 5m
          JWT_CLIENT_TOKEN_EXP_TIME: 5m
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SWITCHER_SLACK_JWT_SECRET: ${{ secrets.SWITCHER_SLACK_JWT_SECRET }}
          SWITCHER_GITOPS_JWT_SECRET: ${{ secrets.SWITCHER_GITOPS_JWT_SECRET }}
          GOOGLE_RECAPTCHA_SECRET: ${{ secrets.GOOGLE_RECAPTCHA_SECRET }}
          GOOGLE_SKIP_AUTH: false
          MAX_STRATEGY_OPERATION: 100
          RELAY_BYPASS_HTTPS: true
          RELAY_BYPASS_VERIFICATION: true
          PERMISSION_CACHE_ACTIVATED: true
          METRICS_ACTIVATED: true
          METRICS_MAX_PAGE: 50
          MAX_REQUEST_PER_MINUTE: 0
          SWITCHER_API_ENABLE: false
          SWITCHER_API_LOGGER: false
  
  docker:
    name: Publish Docker Image
    needs: [ build-test ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: trackerforce/switcher-api
          tags: ${{ github.event.inputs.tag }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
