name: Release CI

on:
  release:
    types: [ created ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 8.0

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: "--experimental-vm-modules"
          MONGODB_URI: mongodb://127.0.0.1:27017/switcher-api-test
          HISTORY_ACTIVATED: true
          JWT_ADMIN_TOKEN_RENEW_INTERVAL: 5m
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SWITCHER_SLACK_JWT_SECRET: ${{ secrets.SWITCHER_SLACK_JWT_SECRET }}
          SWITCHER_GITOPS_JWT_SECRET: ${{ secrets.SWITCHER_GITOPS_JWT_SECRET }}
          GOOGLE_RECAPTCHA_SECRET: ${{ secrets.GOOGLE_RECAPTCHA_SECRET }}
          GOOGLE_SKIP_AUTH: false
          MAX_STRATEGY_OPERATION: 100
          RELAY_BYPASS_HTTPS: true
          RELAY_BYPASS_VERIFICATION: true
          PERMISSION_CACHE_ACTIVATED: true
          METRICS_MAX_PAGE: 50
          SAML_ENTRY_POINT: http://localhost:3000/sso/saml
          SAML_CALLBACK_ENDPOINT_URL: http://localhost:3000
          SAML_REDIRECT_ENDPOINT_URL: http://localhost:4200
          SAML_CERT: SAML_CERT
          SESSION_SECRET: SESSION_SECRET
          SWITCHER_API_ENABLE: false
          SWITCHER_API_LOGGER: false
  
  docker:
    name: Publish Docker Image
    needs: [ build-test ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: trackerforce/switcher-api
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
